# Generated by Django 2.1.4 on 2019-01-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barreau',
        ),
        migrations.DeleteModel(
            name='Plaque',
        ),
    ]
