# Generated by Django 2.1.4 on 2019-01-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20190106_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barreau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(blank=True, default=None, null=True)),
                ('b', models.FloatField(blank=True, default=None, null=True)),
                ('l', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(blank=True, default=None, null=True)),
                ('b', models.FloatField(blank=True, default=None, null=True)),
                ('l', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
