# Generated by Django 2.1.4 on 2019-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_barreau_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barreau',
            name='a',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Dimension a of bar'),
        ),
        migrations.AlterField(
            model_name='barreau',
            name='b',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Dimension b of bar'),
        ),
        migrations.AlterField(
            model_name='barreau',
            name='l',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Dimension l of bar'),
        ),
    ]
