# Generated by Django 2.1.4 on 2019-01-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190109_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(blank=True, default=None, null=True)),
                ('b', models.FloatField(blank=True, default=None, null=True)),
                ('l', models.FloatField(blank=True, default=None, null=True)),
                ('csvfile', models.FileField(default=None, upload_to='', verbose_name='CSV upload (optional)')),
            ],
        ),
        migrations.DeleteModel(
            name='Plaque',
        ),
    ]
