# Generated by Django 2.1.4 on 2019-01-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190110_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='a',
            field=models.FloatField(default=None, verbose_name='Length of bar (m) - dimension a'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='b',
            field=models.FloatField(default=None, verbose_name='Width of bar (m) - dimension b'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='l',
            field=models.FloatField(default=None, verbose_name='Height of bar (m) - dimension l'),
        ),
    ]
