# Generated by Django 2.1.4 on 2019-01-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190110_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='a',
            field=models.FloatField(default=None, verbose_name='Length of plate (m) - dimension a'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='b',
            field=models.FloatField(default=None, verbose_name='Width of plate (m) - dimension b'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='l',
            field=models.FloatField(default=None, verbose_name='Height of plate (m) - dimension l'),
        ),
    ]
